"""Requirements traceability (REQ-DEV-CI-002, REQ-DEV-DOC-001).

Parses tests/features/*.feature, fails if a scenario lacks an ID, an EARS tag or a persona tag,
or if an ID is duplicated, and writes docs/requirements.md. Run with --check to verify the
committed table is current without rewriting it.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FEATURES = ROOT / "tests" / "features"
OUTPUT = ROOT / "docs" / "requirements.md"

REQ_ID = re.compile(r"^(REQ-[A-Z]+-[A-Z]+-\d{3})\s")
EARS = {"ears_ubiquitous", "ears_event_driven", "ears_state_driven", "ears_unwanted_behavior", "ears_optional"}
PERSONAS = {"member", "raid_leader", "maintainer"}


@dataclass(frozen=True)
class Requirement:
    id: str
    text: str
    pattern: str
    personas: tuple[str, ...]
    phases: tuple[str, ...]
    pending: bool
    source: str


def parse(features: Path = FEATURES) -> tuple[list[Requirement], list[str]]:
    reqs: list[Requirement] = []
    errors: list[str] = []
    for path in sorted(features.glob("*.feature")):
        tags: list[str] = []
        for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            line = raw.strip()
            where = f"{path.name}:{lineno}"
            if line.startswith("@"):
                tags += [t.lstrip("@") for t in line.split()]
            elif line.startswith(("Scenario:", "Scenario Outline:")):
                title = line.split(":", 1)[1].strip()
                m = REQ_ID.match(title + " ")
                pattern = [t for t in tags if t in EARS]
                personas = tuple(t for t in tags if t in PERSONAS)
                if not m:
                    errors.append(f"{where}: scenario has no REQ id: {title!r}")
                elif len(pattern) != 1:
                    errors.append(f"{where}: {m.group(1)} needs exactly one EARS tag")
                elif not personas:
                    errors.append(f"{where}: {m.group(1)} has no persona tag")
                else:
                    reqs.append(
                        Requirement(
                            id=m.group(1),
                            text=title[len(m.group(1)) :].strip(),
                            pattern=pattern[0].removeprefix("ears_"),
                            personas=personas,
                            phases=tuple(
                                t.removeprefix("phase_").replace("_", ".") for t in tags if t.startswith("phase_")
                            ),
                            pending="pending" in tags,
                            source=path.name,
                        )
                    )
                tags = []
    seen: set[str] = set()
    for r in reqs:
        if r.id in seen:
            errors.append(f"duplicate requirement id {r.id}")
        seen.add(r.id)
    return reqs, errors


def render(reqs: list[Requirement]) -> str:
    done = sum(not r.pending for r in reqs)
    lines = [
        "# Requirements",
        "",
        "Generated by `just reqs` from `tests/features/`. Do not edit by hand.",
        "",
        f"{len(reqs)} requirements, {done} implemented, {len(reqs) - done} pending.",
        "",
        "| ID | Pattern | Persona | Phase | Status | Requirement |",
        "|---|---|---|---|---|---|",
    ]
    for r in sorted(reqs, key=lambda r: r.id):
        status = "pending" if r.pending else "implemented"
        text = r.text.replace("|", "\\|")
        lines.append(f"| {r.id} | {r.pattern} | {', '.join(r.personas)} | {', '.join(r.phases)} | {status} | {text} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    reqs, errors = parse()
    for e in errors:
        print(e, file=sys.stderr)
    if errors:
        return 1
    table = render(reqs)
    if "--check" in argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != table:
            print("docs/requirements.md is stale; run `just reqs`", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(table, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(reqs)} requirements)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
